cmdargs:
  # Checking more strictly
  severity: style_problem
  # Enable coloring
  color: true
  # Enable Neovim syntax
  env:
    neovim: true

policies:
  # Disable a violation
  ProhibitNoAbortFunction:
    enabled: false
